### ISSUE TITLE
over opslaan enzo

### ISSUE THREAD

**Issue by NinaAalfs** [tweedegolf/ervaringskompas#13]
Hoi Marlon,

Sorry dat het even stil was. Het ziet er mooi uit en iedereen is erg enthousiast.
Een paar dingetjes:
- bij de knop 'bestand downloaden' verschijnt een onleesbaar tekstbestand. Kan dat anders? 
- -Bij 'bestand laden' gaat er een (verkenner) menu open en zie je de tekst 'bestand openen'. Moet je hier een oude versie openen? 

Zou het niet beter zijn om 'bestand opslaan op computer' als knop te hebben? 
En bovenaan in het document: laad eerdere versie?

**Comment by marlonbaeten** [comment]
Ik heb een extra knop toegevoegd en de opties iets verduidelijkt met teksten / icoontjes:

![image](https://github.com/user-attachments/assets/6fb4bce7-9061-4587-bc96-031d33664f64)
