### ISSUE TITLE
Feedback ervaringskompas

### ISSUE THREAD

**Issue by NinaAalfs** [tweedegolf/ervaringskompas#9]
Het volgende valt op:

- Het ziet er overzichtelijk uit
- Het is wel behoorlijk kaal en basic qua uitstraling
- Als je de een van de thema’s scoort op ‘geen ervaring’, krijg je toch circa 20% in het balkje te zien. Kennelijk begint de telling toch nog niet bij 0.
- Het markeren/vlaggetje werkt toch nog niet intuïtief genoeg.
- Er zit een typfout in het lijstje als je een item markeert

Suggesties:

- [x]  Meer kleur. Bijvoorbeeld door om ieder thema heen een gekleurd vak te zetten. Dan ziet het er minder kaal uit
- [x]  Een extra tekstuele toelichting bij de markeer functie: Markeren kan door het vakje rechts te selecteren. Dit mag je gebruiken als je hier bijvoorbeeld extra aandacht aan wilt besteden of een vraag over hebt. Onder aan de pagina verschijnt een lijst van gemarkeerde items. 
- [x]  De schaal bij 0 beginnen, zodat geen ervaring niet meetelt

**Comment by marlonbaeten** [comment]
@NinaAalfs dank voor de feedback! Ik heb een aantal aanpassing live gezet: https://ervaringskompas.nl/

**Comment by NinaAalfs** [comment]
Hoi Marlon,
Dankjewel! Ik heb de feedback verzameld en de volgende punten komen aan bod:
•	Het ziet er met de kleuren al veel aantrekkelijker uit. De kleuren van de laatste 2 thema’s komen niet zo goed overeen met de originele kleuren. Kan dat nog een beetje aangepast worden? (de gele kleur en blauwgrijze kleur)
•	In het lijstje met gemarkeerde ervaringen zie je niet meer terug bij welk thema het item hoort. Kan dit nog anders? (dan zegt het je meer als aios). Bijvoorbeeld: Korte episodezorg: voert aanvullende diagnostiek uit.
•	We willen nog graag 2 kleine plaatjes toevoegen helemaal bovenaan. Het Voha logo. En een plaatje van een kompas. Het Voha logo stuur ik je. Qua plaatjes vroegen we ons af of jij toegang hebt tot een beeldbank met foto’s/plaatjes waar geen rechten op zitten?
•	We willen nog een iets langer introstukje toevoegen, omdat je met het webadres direct in het ervaringskompas landt. Je mag de volgende tekst toevoegen (ipv de huidige zin):
o	Als huisarts in opleiding is het de bedoeling om uiteindelijk op alle huisartgeneeskundige thema’s ervaring en bekwaamheid op te bouwen. Dit ervaringskompas is bedoeld als reflectie instrument om zelf in kaart te brengen welke ervaring je -in de breedte en diepte van het vak- hebt kunnen opdoen. Op basis daarvan kun je je leerproces in de praktijk verder vorm en richting te geven.
